spring:
    datasource:
        url: jdbc:postgresql://host.docker.internal:5431/book_storage
        username: librarian
        password: 9en2w0oc
    jpa:
        hibernate:
            ddl-auto: update
logging:
    level:
        root: debug